## Configuration to run the limit calculator
## Physics models and constans
physics:
  ## True energy flux spectra
  isotope_flux:
    U235: "data/mueller.root:g_U235"
    U238: "data/mueller.root:g_U238"
    Pu239: "data/mueller.root:g_Pu239"
    Pu241: "data/mueller.root:g_Pu241"
    #U245: "data/huber.root:g_U245"
    #Pu239: "data/huber.root:g_Pu239"
    #Pu241: "data/huber.root:g_Pu241"

  ## IBD cross section
  #ibd_xsec: "data/ibdxsec.root:g_HighE"
  ibd_xsec: "data/ibdxsec.root:g_LowE"

  ## Oscillation parameters
  oscillation:
    sin12: [0.852, 0.013]  ## sin^2(2theta_12), solar neutrinos, ignored in our tool
    sin13: [0.085, 0.005] ## sin^2(2theta_13), reactor neutrinos
    sin23: [0.976, 0.020]  ## sin^2(2theta_23), atmospheric neutrinos, ignored in our tool
    dm21: [7.53e-5, 1.8e-6] ## delta m^2_21 (eV^2), ignored in our tool
    dm31: [2.45e-3, 3.0e-5] ## delta m^2_32 (eV^2), Normal ordering
    delta_cp: [195, 25] ## degree, T2K(2021) and NOvA

## Detector configuration
detectors:
  - name: RENE0
    position: [20.0, 0, -11.36] ## Location to be decided
    efficiency: 0.8 ## To be updated
    n_protons: 2.1e28 ## To be updated
    #response: "data/response_ibd_gaus.root:hResp_ENu_vs_Ereco" ## response matrix TH2D, (x=E_nu, y=E_reco)
    response: "data/response_gaus.root:hResp_ETrue_vs_EReco" ## response matrix TH2D, (x=E_nu, y=E_reco)
    #response: "/users/cpnr/wonsang1995/work/RAT_0611/renesim/test/work7/Resolution_like_RENO/resolution_IBD/IDEAL2.root:h_resonse_5" ## RENE IDEAL geometry
    #response: "/users/cpnr/wonsang1995/work/RAT_0611/renesim/test/work7/Resolution_like_RENO/resolution_IBD/RECENT2.root:h_resonse_5" ## RENE IDEAL geometry

## Reactor configuration
## Locations are found from Nucler Engineering and Technology 49 (2017) 813-819
## Thermal power is taken from homepages
reactors:
  - name: Hanbit6
    position: [0.0, 0.0, 0.0] # [x,y,z] in meters
    power: 2.815 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
  - name: Hanbit5
    position: [-217.7, -146.7, 0] # [x,y,z] in meters
    power: 2.815 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
  - name: Hanbit4
    position: [-408.2, -300.0, 0.0] # [x,y,z] in meters
    power: 2.815 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
  - name: Hanbit3
    position: [-616.8, -454.4, 0.0] # [x,y,z] in meters
    power: 2.815 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
  - name: Hanbit2
    position: [-816.4, -597.2, 0.0] # [x,y,z] in meters
    power: 2.775 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
  - name: Hanbit1
    position: [-1034.1, -750.0, 0.0] # [x,y,z] in meters
    power: 2.775 # Thermal power in GW
    elements:
      name: [U235, U238, Pu239, Pu241]
      fraction: [0.58, 0.08, 0.30, 0.04]
